version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/dummy.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
        
