version: 0.0
os: windows
files:
  - source: publish
    destination: C:\inetpub\wwwroot\MyApp
hooks:
  BeforeInstall:
    - location: scripts/before-install.ps1
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.ps1
      timeout: 300
