version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - dotnet restore
  build:
    commands:
      - echo "Building the project..."
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo "Creating deployment package..."
      - dotnet publish -c Release -o output
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - output/**/*
  discard-paths: no
